<?php

use App\Models\District;
use App\Models\FieldOfStudy;
use App\Models\PrescribedSpecialization;
use App\Models\Region;
use App\Models\TypeOfStudy;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class PopulateStaticData extends Migration
{
    public function up()
    {
        $raw_regions = [
            '1', 'Hlavní město Praha',
            '2', 'Jihočeský kraj',
            '3', 'Jihomoravský kraj',
            '4', 'Karlovarský kraj',
            '5', 'Kraj Vysočina',
            '6', 'Královéhradecký kraj',
            '7', 'Liberecký kraj',
            '8', 'Moravskoslezský kraj',
            '9', 'Olomoucký kraj',
            '10', 'Pardubický kraj',
            '11', 'Plzeňský kraj',
            '12', 'Středočeský kraj',
            '13', 'Ústecký kraj',
            '14', 'Zlínský kraj',
        ];

        for($i = 0; $i < count($raw_regions); $i += 2){
            Region::create([
                'id' => $raw_regions[$i],
                'name' => $raw_regions[$i + 1],
            ]);
        }

        $raw_neighboring_regions = [
            '1', '12',
            '2', '11',
            '2', '12',
            '2', '5',
            '2', '3',
            '3', '2',
            '3', '5',
            '3', '10',
            '3', '9',
            '3', '14',
            '4', '11',
            '4', '7',
            '4', '12',
            '5', '2',
            '5', '3',
            '5', '12',
            '5', '10',
            '6', '7',
            '6', '12',
            '6', '10',
            '7', '13',
            '7', '12',
            '7', '6',
            '8', '9',
            '8', '14',
            '9', '8',
            '9', '14',
            '9', '3',
            '9', '10',
            '10', '6',
            '10', '12',
            '10', '5',
            '10', '3',
            '10', '9',
            '11', '13',
            '11', '4',
            '11', '2',
            '11', '12',
            '12', '1',
            '12', '11',
            '12', '2',
            '12', '5',
            '12', '10',
            '12', '6',
            '12', '7',
            '12', '13',
            '13', '4',
            '13', '11',
            '13', '12',
            '13', '7',
            '14', '3',
            '14', '9',
            '14', '8',
        ];

        for($i = 0; $i < count($raw_neighboring_regions); $i += 2){
            $master_id = $raw_neighboring_regions[$i];
            $neighbor_id = $raw_neighboring_regions[$i + 1];
            DB::insert("INSERT INTO neighboring_regions (master_id, neighbor_id, created_at, updated_at) VALUES ($master_id, $neighbor_id, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP )");
        }

        $raw_districts = [
            '1', 'Praha', '1',
            '2', 'České Budějovice', '2',
            '3', 'Český Krumlov', '2',
            '4', 'Jindřichův Hradec', '2',
            '5', 'Písek', '2',
            '6', 'Prachatice', '2',
            '7', 'Strakonice', '2',
            '8', 'Tábor', '2',
            '9', 'Blansko', '3',
            '10', 'Brno-město', '3',
            '11', 'Brno-venkov', '3',
            '12', 'Břeclav', '3',
            '13', 'Hodonín', '3',
            '14', 'Vyškov', '3',
            '15', 'Znojmo', '3',
            '16', 'Cheb', '4',
            '17', 'Karlovy Vary', '4',
            '18', 'Sokolov', '4',
            '19', 'Havlíčkův Brod', '5',
            '20', 'Jihlava', '5',
            '21', 'Pelhřimov', '5',
            '22', 'Třebíč', '5',
            '23', 'Žďár nad Sázavou', '5',
            '24', 'Hradec Králové', '6',
            '25', 'Jičín', '6',
            '26', 'Náchod', '6',
            '27', 'Rychnov nad Kněžnou', '6',
            '28', 'Trutnov', '6',
            '29', 'Česká Lípa', '7',
            '30', 'Jablonec nad Nisou', '7',
            '31', 'Liberec', '7',
            '32', 'Semily', '7',
            '33', 'Bruntál', '8',
            '34', 'Frýdek-Místek', '8',
            '35', 'Karviná', '8',
            '36', 'Nový Jičín', '8',
            '37', 'Opava', '8',
            '38', 'Ostrava-město', '8',
            '39', 'Jeseník', '9',
            '40', 'Olomouc', '9',
            '41', 'Prostějov', '9',
            '42', 'Přerov', '9',
            '43', 'Šumperk', '9',
            '44', 'Chrudim', '10',
            '45', 'Pardubice', '10',
            '46', 'Svitavy', '10',
            '47', 'Ústí nad Orlicí', '10',
            '48', 'Domažlice', '11',
            '49', 'Klatovy', '11',
            '50', 'Plzeň-jih', '11',
            '51', 'Plzeň-město', '11',
            '52', 'Plzeň-sever', '11',
            '53', 'Rokycany', '11',
            '54', 'Tachov', '11',
            '55', 'Benešov', '12',
            '56', 'Beroun', '12',
            '57', 'Kladno', '12',
            '58', 'Kolín', '12',
            '59', 'Kutná Hora', '12',
            '60', 'Mělník', '12',
            '61', 'Mladá Boleslav', '12',
            '62', 'Nymburk', '12',
            '63', 'Praha-východ', '12',
            '64', 'Praha-západ', '12',
            '65', 'Příbram', '12',
            '66', 'Rakovník', '12',
            '67', 'Děčín', '13',
            '68', 'Chomutov', '13',
            '69', 'Litoměřice', '13',
            '70', 'Louny', '13',
            '71', 'Most', '13',
            '72', 'Teplice', '13',
            '73', 'Ústí nad Labem', '13',
            '74', 'Kroměříž', '14',
            '75', 'Uherské Hradiště', '14',
            '76', 'Vsetín', '14',
            '77', 'Zlín', '14',
        ];

        for($i = 0; $i < count($raw_districts); $i += 3){
            District::create([
                'id' => $raw_districts[$i],
                'name' => $raw_districts[$i + 1],
                'region_id' => $raw_districts[$i + 2],
            ]);
        }

        $tos = [
            '1', 'K', 'maturita - gymnázium',
            '2', 'M', 'maturita - střední odborná škola',
            '3', 'L0', 'výuční list s maturitou',
            '4', 'L5', 'nástavby - maturita',
            '5', 'H', 'výuční list'
        ];

        for($i = 0; $i < count($tos); $i += 3){
            TypeOfStudy::create([
                'id' => $tos[$i],
                'code' => $tos[$i + 1],
                'name' => $tos[$i + 2],
            ]);
        }

        $fos = [
            '1', 'Gymnázia', '1',
            '2', 'Lycea', '2',
            '3', 'SOŠ ekonomické', '2',
            '4', 'SOŠ hotelové a podnikatelské', '2',
            '5', 'SOŠ pedagogické a humanitní', '2',
            '6', 'SOŠ technické 1', '2',
            '7', 'SOŠ technické 2', '2',
            '8', 'SOŠ umělecké', '2',
            '9', 'SOŠ zdravotnické', '2',
            '10', 'SOŠ zemědělské', '2',
            '11', 'SOU technické', '3',
            '12', 'SOU ostatní', '3',
            '13', 'SOU nástavby technické', '4',
            '14', 'SOU nástavby ostatní', '4',
        ];

        for($i = 0; $i < count($fos); $i += 3){
            FieldOfStudy::create([
                'id' => $fos[$i],
                'name' => $fos[$i + 1],
                'type_of_study_id' => $fos[$i + 2],
            ]);
        }

        $ps = [
            'Gymnázium - 4 leté', '79-41-K/41', '1',
            'Gymnázium se sportovní přípravou - 4 leté', '79-42-K/41', '1',
            'Gymnázium - 6 leté', '79-41-K/61', '1',
            'Gymnázium se sportovní přípravou - 6 leté', '79-42-K/61', '1',
            'Gymnázium - 8 leté', '79-41-K/81', '1',
            'Gymnázium se sportovní přípravou - 8 leté', '79-42-K/81', '1',
            'Technické lyceum', '78-42-M/01', '2',
            'Ekonomické lyceum', '78-42-M/02', '2',
            'Pedagogické lyceum', '78-42-M/03', '2',
            'Zdravotnické lyceum', '78-42-M/04', '2',
            'Přírodovědné lyceum', '78-42-M/05', '2',
            'Kombinované lyceum', '78-42-M/06', '2',
            'Vojenské lyceum', '78-42-M/07', '2',
            'Obchodní akademie', '63-41-M/02', '3',
            'Ekonomika a podnikání', '63-41-M/01', '4',
            'Hotelnictví', '65-42-M/01', '4',
            'Cestovní ruch', '65-42-M/02', '4',
            'Knihkupecké a nakladatelské činnosti', '66-43-M/01', '5',
            'Bezpečnostně právní činnost', '68-42-M/01', '5',
            'Veřejnosprávní činnost', '68-43-M/01', '5',
            'Informační služby', '72-41-M/01', '5',
            'Předškolní a mimoškolní pedagogika', '75-31-M/01', '5',
            'Pedagogika pro asistenty ve školství', '75-31-M/02', '5',
            'Sociální činnost', '75-41-M/01', '5',
            'Informační technologie', '18-20-M/01', '6',
            'Strojírenství', '23-41-M/01', '6',
            'Dopravní prostředky', '23-45-M/01', '6',
            'Elektrotechnika', '26-41-M/01', '6',
            'Telekomunikace', '26-45-M/01', '6',
            'Aplikovaná chemie', '28-44-M/01', '6',
            'Stavební materiály', '36-43-M/01', '6',
            'Technická zařízení budov', '36-45-M/01', '6',
            'Stavebnictví', '36-47-M/01', '6',
            'Geotechnika', '21-42-M/01', '7',
            'Hutnictví', '21-43-M/01', '7',
            'Technologie silikátů', '28-46-M/01', '7',
            'Technologie potravin', '29-41-M/01', '7',
            'Analýza potravin', '29-42-M/01', '7',
            'Textilnictví', '31-41-M/01', '7',
            'Oděvnictví', '31-43-M/01', '7',
            'Zpracování usní, plastů a pryže', '32-41-M/01', '7',
            'Nábytkářská a dřevařská výroba', '33-42-M/01', '7',
            'Polygrafie', '34-41-M/01', '7',
            'Obalová technika', '34-42-M/01', '7',
            'Geodézie a katastr nemovitostí', '36-46-M/01', '7',
            'Provoz a ekonomika dopravy', '37-41-M/01', '7',
            'Logistické a finanční služby', '37-42-M/01', '7',
            'Požární ochrana', '39-08-M/01', '7',
            'Užitá malba', '82-41-M/01', '8',
            'Užitá fotografie a média', '82-41-M/02', '8',
            'Scénická a výstavní tvorba', '82-41-M/03', '8',
            'Průmyslový design', '82-41-M/04', '8',
            'Grafický design', '82-41-M/05', '8',
            'Výtvarné zpracování kovů a drahých kamenů', '82-41-M/06', '8',
            'Modelářství a návrhářství oděvů', '82-41-M/07', '8',
            'Tvorba hraček a herních předmětů', '82-41-M/08', '8',
            'Modelářství a návrhářství obuvi a módních doplňků', '82-41-M/09', '8',
            'Řezbářství', '82-41-M/10', '8',
            'Design interiéru', '82-41-M/11', '8',
            'Výtvarné zpracování keramiky a porcelánu', '82-41-M/12', '8',
            'Výtvarné zpracování skla a světelných objektů', '82-41-M/13', '8',
            'Textilní výtvarnictví', '82-41-M/14', '8',
            'Tvorba a vzorování bižuterie', '82-41-M/15', '8',
            'Kamenosochařství', '82-41-M/16', '8',
            'Multimediální tvorba', '82-41-M/17', '8',
            'Uměleckořemeslná stavba varhan', '82-41-M/18', '8',
            'Konzervátorství a restaurátorství', '82-42-M/01', '8',
            'Hudba', '82-44-M/01', '8',
            'Hudba', '82-44-P/01', '8',
            'Zpěv', '82-45-M/01', '8',
            'Zpěv', '82-45-P/01', '8',
            'Současný tanec', '82-46-M/02', '8',
            'Hudebně dramatické umění', '82-47-M/01', '8',
            'Hudebně dramatické umění', '82-47-P/01', '8',
            'Zdravotnický asistent', '53-41-M/01', '9',
            'Nutriční asistent', '53-41-M/02', '9',
            'Laboratorní asistent', '53-43-M/01', '9',
            'Ortoticko - protetický technik', '53-44-M/01', '9',
            'Asistent zubního technika', '53-44-M/03', '9',
            'Oční optik', '69-42-M/01', '9',
            'Ekologie a životní prostředí', '16-01-M/01', '10',
            'Průmyslová ekologie', '16-02-M/01', '10',
            'Rostlinolékařství', '41-04-M/01', '10',
            'Agropodnikání', '41-41-M/01', '10',
            'Vinohradnictví', '41-42-M/01', '10',
            'Rybářství', '41-43-M/01', '10',
            'Chovatelství', '41-43-M/02', '10',
            'Zahradnictví', '41-44-M/01', '10',
            'Mechanizace a služby', '41-45-M/01', '10',
            'Lesnictví', '41-46-M/01', '10',
            'Veterinářství', '43-41-M/01', '10',
            'Hutník operátor', '21-43-L/01', '11',
            'Technik modelových zařízení', '21-44-L/01', '11',
            'Mechanik strojů a zařízení', '23-44-L/01', '11',
            'Mechanik seřizovač', '23-45-L/01', '11',
            'Letecký mechanik', '23-45-L/02', '11',
            'Optik', '23-62-L/01', '11',
            'Technik - puškař', '23-69-L/01', '11',
            'Mechanik elektrotechnik', '26-41-L/01', '11',
            'Chemik operátor', '28-42-L/01', '11',
            'Oděvní technik', '31-43-L/01', '11',
            'Operátor dřevařské a nábytkářské výroby', '33-41-L/01', '11',
            'Autotronik', '39-41-L/01', '11',
            'Mechanik instalatérských a elektrotechnických zařízení', '39-41-L/02', '11',
            'Tiskař na polygrafických strojích', '34-52-L/01', '12',
            'Reprodukční grafik pro média', '34-53-L/01', '12',
            'Fotograf', '34-56-L/01', '12',
            'Technik dokončovacího zpracování tiskovin', '34-57-L/01', '12',
            'Chovatel cizokrajných zvířat', '41-43-L/01', '12',
            'Gastronomie', '65-41-L/01', '12',
            'Obchodník', '66-41-L/01', '12',
            'Kosmetické služby', '69-41-L/01', '12',
            'Masér sportovní a rekondiční', '69-41-L/02', '12',
            'Starožitník', '82-48-L/01', '12',
            'Uměleckořemeslné zpracování kovů', '82-51-L/01', '12',
            'Uměleckořemeslné zpracování dřeva', '82-51-L/02', '12',
            'Uměleckořemeslné zpracování textilu', '82-51-L/03', '12',
            'Uměleckořemeslné zpracování kamene a keramiky', '82-51-L/04', '12',
            'Uměleckořemeslné zpracování skla', '82-51-L/05', '12',
            'Uměleckořemeslná stavba hudebních nástrojů', '82-51-L/06', '12',
            'Provozní technika', '23-43-L/51', '13',
            'Mechanik elektrotechnik', '26-41-L/51', '13',
            'Provozní elektrotechnika', '26-41-L/52', '13',
            'Chemik operátor', '28-42-L/51', '13',
            'Technologie potravin', '29-41-L/51', '13',
            'Nábytkářská a dřevařská výroba', '33-42-L/51', '13',
            'Stavební provoz', '36-44-L/51', '13',
            'Technik plynových zařízení a tepelných soustav', '36-45-L/52', '13',
            'Autotronik', '39-41-L/51', '13',
            'Polygrafický průmysl', '34-41-L/51', '14',
            'Logistické a finanční služby', '37-42-L/51', '14',
            'Rybářství', '41-43-L/51', '14',
            'Trenérství dostihových a sportovních koní', '41-43-L/52', '14',
            'Zahradnictví', '41-44-L/51', '14',
            'Mechanizace zemědělství a lesního hospodářství', '41-45-L/51', '14',
            'Zdravotnický asistent', '53-41-L/51', '14',
            'Podnikání', '64-41-L/51', '14',
            'Gastronomie', '65-41-L/51', '14',
            'Obchodník', '66-41-L/51', '14',
            'Propagace', '66-42-L/51', '14',
            'Bezpečnostní služby', '68-42-L/51', '14',
            'Masér sportovní a rekondiční', '69-41-L/51', '14',
            'Vlasová kosmetika', '69-41-L/52', '14',
            'Sociální činnost', '75-41-L/51', '14',
            'Umělecké řemeslné práce', '82-51-L/51', '14',
        ];

        for($i = 0; $i < count($ps); $i += 3){
            PrescribedSpecialization::create([
                'name' => $ps[$i],
                'code' => $ps[$i + 1],
                'field_of_study_id' => $ps[$i + 2],
            ]);
        }    }

    public function down()
    {
        Schema::table('', function(Blueprint $table){
            //
        });
    }
}
